# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_accepted_answer',
            field=models.BooleanField(default=False),
        ),
    ]
