# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_has_accepted_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='descritpion',
            new_name='descriptpion',
        ),
    ]
