# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170308_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='descriptpion',
            new_name='description',
        ),
    ]
