# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170308_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='descritpion',
            new_name='description',
        ),
    ]
